services:
  server:
    image: python:3.12-slim
    container_name: lan-server
    command: python -m http.server 8000 --bind 0.0.0.0
    ports:
      - "8000:8000" # Seems to be working for external lan
