services:
  password-evaluator:
    build: app
    container_name: flask_backend
    restart: unless-stopped
    # Port 5000 není vystaven ven, je dostupný jen pro Nginx uvnitř sítě

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/cert.pem:/etc/nginx/ssl/cert.pem:ro
      - ./nginx/key.pem:/etc/nginx/ssl/key.pem:ro
    depends_on:
      - password-evaluator
    restart: unless-stopped
