services:
  qr-gen:
    image: nginx:alpine
    container_name: qr_generator_web
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    restart: unless-stopped
